name: Sweep
favicon: null
layout_spectrum: 0.6330197725910693
typography_spectrum: 0.03952912543900311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.33028598222881556
  lightness: 0.1533188079483807
  saturation: 0.4353351241443306
  rhythmicContrast: 0.8872597359586507
purpose: []
